<h3> Question 1 </h3>
This question explores some of basic functionality needed for investigating the EM dataset.

#### 1. Import the key modules and set parameters

In [190]:
#a)
from meshparty import trimesh_io, trimesh_vtk
from analysisdatalink.datalink_ext import AnalysisDataLinkExt as AnalysisDataLink
import numpy as np
import pandas as pd
import vtkplotter



#b)
dataset_name = 'pinky100'
data_version = 175
sqlalchemy_database_uri = 'postgres://postgres:welcometothematrix@swdb-em-db.crjvviai1xxh.us-west-2.rds.amazonaws.com'
dl = AnalysisDataLink(dataset_name=dataset_name,
                      sqlalchemy_database_uri=sqlalchemy_database_uri,
                      materialization_version=data_version,
                      verbose=False)

#c)
mesh_folder = "/data/dynamic_brain_workshop/electron_microscopy/2019/"
voxel_resolution = np.array([4,4,40])

#### 2. From the database, find all synapses that are manually annotated.

In [161]:
#find all synapses
all_man_syn = dl.query_synapses('synapse_ai_manual_v2')

#### 3. Find the post_synaptic cell id (post_pt_root_id) with the most synapses that are manually annotated. (Hint, this cell has 34 synapses manually annotated)

In [162]:
all_man_syn['syn_num']=all_man_syn.groupby('post_pt_root_id')['id'].transform(len)
cellid = all_man_syn[all_man_syn.syn_num==34]['post_pt_root_id'].values[0]
print(cellid)

648518346349519412


#### 4. Visualize this cell

In [156]:
mm = trimesh_io.MeshMeta(disk_cache_path='test/test_files')
mesh = mm.mesh(filename ='/data/dynamic_brain_workshop/electron_microscopy/2019/meshes/%d.h5'%cellid)
mesh_poly =trimesh_vtk.trimesh_to_vtk(mesh.vertices,mesh.faces,None)
plt_actor = vtkplotter.Actor(mesh_poly)


vtkplotter.embedWindow(backend='k3d')
vp = vtkplotter.Plotter(bg='b')
myactor = vtkplotter.Actor(plt_actor, c='r')
myactor.GetMapper().Update()
vp+=myactor
vp.show()

Plot(antialias=3, axes=['x', 'y', 'z'], background_color=16777215, camera=[335229.1004316527, 228964.600431652…

#### 5. Find the 10 largest synapses that have been automatically extracted on this cell. (use pni_synapses_i3)


In [189]:
post_synapse_df = dl.query_synapses('pni_synapses_i3', post_ids = np.array([cellid]))
biggest_synapses = post_synapse_df.sort_values(by=['size'],ascending=False).head(10)
print(biggest_synapses)


           id  valid        pre_pt_position  pre_pt_supervoxel_id  \
5019  3322346   True    [75846, 40538, 532]     92929640447876967   
4428  2960634   True   [81808, 39688, 2093]     94335967359410942   
857    556228   True   [60808, 58234, 1960]     88726254739530694   
158    163518   True    [82348, 41354, 796]     94619598409703500   
828    569849   True   [86124, 47150, 1948]     95752134041011906   
4131  2837065   True  [111232, 50494, 1510]    102510814837100455   
4130  2837000   True   [88188, 57930, 1641]     96326066225829934   
2507  1735670   True   [85836, 46216, 1942]     95469559552675983   
3721  2596530   True    [75592, 41264, 546]     92649264982796392   
4159  2836673   True    [79842, 64456, 488]     93799349850494311   

          pre_pt_root_id        ctr_pt_position       post_pt_position  \
5019  648518346349513602    [76018, 40597, 539]    [75820, 40594, 533]   
4428  648518346346298862   [81906, 39632, 2109]   [81762, 39704, 2095]   
857   648518346341

#### 6. Visualize the cell and these 10 synapses, with the synapse radius corresponding to the synapse size.

In [204]:
mm = trimesh_io.MeshMeta(disk_cache_path='test/test_files')
mesh = mm.mesh(filename ='/data/dynamic_brain_workshop/electron_microscopy/2019/meshes/%d.h5'%cellid)
mesh_poly =trimesh_vtk.trimesh_to_vtk(mesh.vertices,mesh.faces,None)
plt_actor = vtkplotter.Actor(mesh_poly)


syn_pts = np.vstack(biggest_synapses['ctr_pt_position'].values) * voxel_resolution
syn_sizes = biggest_synapses['size']
syn_actors = trimesh_vtk.point_cloud_actor(syn_pts, size=syn_sizes.values)


vtkplotter.embedWindow(backend='k3d')
vp = vtkplotter.Plotter(bg='b')
myactor = vtkplotter.Actor(plt_actor, c='r')
myactor.GetMapper().Update()
vp+=myactor
mysynactor = vtkplotter.Actor(syn_actors, c='b')
mysynactor.GetMapper().Update()
vp+= mysynactor




vp.show()


[[304072 162388  21560]
 [327624 158528  84360]
 [243780 233344  78360]
 [330036 165472  31720]
 [345064 188512  77920]
 [445496 201752  60360]
 [353264 231600  65720]
 [343812 184440  77760]
 [302904 164872  22200]
 [319368 258080  19320]]
[4722. 3968. 3822. 3522. 3241. 3010. 2994. 2971. 2962. 2918.]


Plot(antialias=3, axes=['x', 'y', 'z'], background_color=16777215, camera=[335234.3805457501, 228969.880545750…